# NOME DA APLICAÇÃO
spring.application.name=actio-api

# H2 DATABASE CONFIG
spring.datasource.url=jdbc:h2:mem:actio_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Inicialização de BD com schema.sql + data.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# PORTA
server.port=8080

# SEGURANÇA / JWT
jwtKey=Y6h9Ds2z!Qx7Ve*pLmR@1tGcZk#FwUdA
apiKey=18V1LSNB7JWPOZBB
iKey=18V1LSNB7JWPOZBB

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true