package com.actio.actio_api.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents the status of an account in the system.
 *
 * Each status instance defines a unique state that can be assigned to one or more accounts.
 * Common statuses may include values like active, suspended, or closed.
 *
 * This entity is referenced by the Account entity to determine the account's current lifecycle state.
 */
@Data
@Entity
@Table(name = "account_status")
public class AccountStatus {

    /**
     * Unique code representing the account status.
     * Serves as the primary key and is auto-generated by the database.
     */
    @Id
    @Column(name = "status_code")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int statusCode;

    /**
     * Human-readable description of the status.
     * Provides context about the account state for internal and external use.
     */
    @Column(name = "status_description")
    private String statusDescription;

}
