package com.actio.actio_api.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents the classification type of financial movement.
 *
 * Each type defines the nature of a transaction recorded in the system,
 * such as deposit, withdrawal, transfer, or correction. This entity enables
 * standardized categorization of movements for reporting, auditing, and business logic.
 *
 * The Movement entity references this type to label the purpose and behavior
 * of each transaction.
 */
@Entity
@Table(name = "movement_type")
@Data
public class MovementType {

    /**
     * Unique identifier for the movement type.
     * Automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "type_code")
    private Integer typeCode;

    /**
     * Human-readable description of the movement type.
     * Helps interpret the intent or category of a transaction.
     */
    @Column(name = "type_description")
    private String typeDescription;

}
