package com.actio.actio_api.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents the classification of a stock transaction.
 *
 * This entity defines the nature of trading operations performed by users,
 * such as "BUY" or "SELL". It enables consistent labeling and interpretation
 * of transactions across the system.
 *
 * The StockTransaction entity references this type to identify the purpose
 * and behavior of each trading operation, helping drive reporting,
 * auditing, and business logic validation.
 */
@Data
@Entity
@Table(name = "transaction_type")
public class TransactionType {

    /**
     * Unique identifier for the transaction type.
     * Auto-generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "type_code")
    private Integer typeCode;

    /**
     * Description of the transaction type.
     * Often corresponds to trading actions such as "BUY" or "SELL".
     */
    @Column(name = "type_description")
    private String typeDescription;

}
